version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    labels: [dependencies]
    groups:
      stable-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: npm
    directory: /templates/Projects/default
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    labels: [dependencies]
    groups:
      template-stable-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Paris
    open-pull-requests-limit: 3
    labels: [dependencies, github-actions]
    groups:
      github-actions:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
